INITIAL_ITEMS = [
    {"id": "item-001", "name": "Beras 50kg", "categoryId": "logistik-dapur", "category": "Logistik Dapur", "currentStock": 500, "minThreshold": 100, "unit": "KG", "description": "Beras sebagai bahan makanan utama"},
    {"id": "item-002", "name": "Mie Instan Kemasan", "categoryId": "logistik-dapur", "category": "Logistik Dapur", "currentStock": 200, "minThreshold": 50, "unit": "DOS", "description": "Mie instan kondisi baik"},
    {"id": "item-003", "name": "Sabun Cuci Baju", "categoryId": "logistik-kebersihan", "category": "Logistik Kebersihan", "currentStock": 300, "minThreshold": 80, "unit": "BUAH", "description": "Sabun cuci baju cair/kotak"},
    {"id": "item-004", "name": "Lampu Sorot 10W", "categoryId": "logistik-listrik", "category": "Logistik Listrik", "currentStock": 50, "minThreshold": 20, "unit": "BUAH", "description": "Lampu sorot LED 10 watt"},
    {"id": "item-005", "name": "Masker Medis 3 Lapis", "categoryId": "logistik-kesehatan", "category": "Logistik Kesehatan", "currentStock": 1000, "minThreshold": 200, "unit": "DOS", "description": "Masker medis 3 lapis sekali pakai"},
    {"id": "item-006", "name": "Seprei Polos 120x200cm", "categoryId": "logistik-pembersihan", "category": "Logistik Pembersihan", "currentStock": 150, "minThreshold": 50, "unit": "METER", "description": "Seprei polos kain katun"},
    {"id": "item-007", "name": "Agar Botol Minum 500ml", "categoryId": "logistik-air-minum", "category": "Logistik Air Minum", "currentStock": 1000, "minThreshold": 300, "unit": "BOTOL", "description": "Botol minum stainless steel 500ml"},
    {"id": "item-008", "name": "Tisu Basah Sanitasi", "categoryId": "logistik-sanitasi", "category": "Logistik Sanitasi", "currentStock": 400, "minThreshold": 100, "unit": "PACK", "description": "Tisu basah antiseptik"},
    {"id": "item-009", "name": "Apar Kecil 5KG", "categoryId": "logistik-apar", "category": "Logistik Apar", "currentStock": 25, "minThreshold": 10, "unit": "BUAH", "description": "Apar 5KG emergency"},
    {"id": "item-010", "name": "Peralatan Makan Set 10 Porsi", "categoryId": "logistik-makanan", "category": "Logistik Makanan", "currentStock": 80, "minThreshold": 30, "unit": "SET", "description": "Peralatan makan stainless 10 porsi"},
    {"id": "item-011", "name": "Kain Pencuci Kasur", "categoryId": "logistik-pembersihan", "category": "Logistik Pembersihan", "currentStock": 120, "minThreshold": 30, "unit": "METER", "description": "Kain pencuci kasur"},
    {"id": "item-012", "name": "Bantuan Peralatan Medis", "categoryId": "logistik-kesehatan", "category": "Logistik Kesehatan", "currentStock": 45, "minThreshold": 15, "unit": "BUAH", "description": "Bantuan peralatan medis darurat"},
    {"id": "item-013", "name": "Senter Cadangan LED", "categoryId": "logistik-listrik", "category": "Logistik Listrik", "currentStock": 75, "minThreshold": 25, "unit": "BUAH", "description": "Senter cadangan LED"},
    {"id": "item-014", "name": "Baterai AA 1.5V", "categoryId": "logistik-listrik", "category": "Logistik Listrik", "currentStock": 500, "minThreshold": 200, "unit": "BUAH", "description": "Baterai AA 1.5V"},
    {"id": "item-015", "name": "Tali Pengaman Kecil", "categoryId": "logistik-peralatan", "category": "Logistik Peralatan", "currentStock": 200, "minThreshold": 50, "unit": "METER", "description": "Tali pengaman kecil"},
    {"id": "item-016", "name": "Masker N95", "categoryId": "logistik-kesehatan", "category": "Logistik Kesehatan", "currentStock": 300, "minThreshold": 100, "unit": "DOS", "description": "Masker N95"},
    {"id": "item-017", "name": "Hand Sanitizer 500ml", "categoryId": "logistik-sanitasi", "category": "Logistik Sanitasi", "currentStock": 250, "minThreshold": 80, "unit": "BUAH", "description": "Hand sanitizer 500ml"},
    {"id": "item-018", "name": "Sarung Tangan Medis", "categoryId": "logistik-kesehatan", "category": "Logistik Kesehatan", "currentStock": 400, "minThreshold": 150, "unit": "DOS", "description": "Sarung tangan medis"},
    {"id": "item-019", "name": "Kotak Pertolongan Pertama", "categoryId": "logistik-kesehatan", "category": "Logistik Kesehatan", "currentStock": 60, "minThreshold": 20, "unit": "BUAH", "description": "Kotak pertolongan pertama (P3K)"},
    {"id": "item-020", "name": "Kertas Toilet Perkantoran", "categoryId": "logistik-perkantoran", "category": "Logistik Perkantoran", "currentStock": 800, "minThreshold": 300, "unit": "ROLL", "description": "Kertas toilet perkantoran"},
    {"id": "item-021", "name": "Tisu Toilet Premium", "categoryId": "logistik-perkantoran", "category": "Logistik Perkantoran", "currentStock": 600, "minThreshold": 200, "unit": "PACK", "description": "Tisu toilet premium"},
    {"id": "item-022", "name": "Galon Air Minum 5L", "categoryId": "logistik-air-minum", "category": "Logistik Air Minum", "currentStock": 200, "minThreshold": 80, "unit": "GALON", "description": "Galon air minum 5 liter"},
    {"id": "item-023", "name": "Water Filter Portable", "categoryId": "logistik-air-minum", "category": "Logistik Air Minum", "currentStock": 40, "minThreshold": 15, "unit": "BUAH", "description": "Water filter portable"},
    {"id": "item-024", "name": "Kantong Plastik Medis", "categoryId": "logistik-sanitasi", "category": "Logistik Sanitasi", "currentStock": 500, "minThreshold": 200, "unit": "DOS", "description": "Kantong plastik medis"},
    {"id": "item-025", "name": "Kantong Plastik Sampah", "categoryId": "logistik-sanitasi", "category": "Logistik Sanitasi", "currentStock": 300, "minThreshold": 100, "unit": "DOS", "description": "Kantong plastik sampah"},
    {"id": "item-026", "name": "Handuk Mandi Putih", "categoryId": "logistik-pembersihan", "category": "Logistik Pembersihan", "currentStock": 250, "minThreshold": 80, "unit": "BUAH", "description": "Handuk mandi putih"},
    {"id": "item-027", "name": "Deterjen Cair", "categoryId": "logistik-pembersihan", "category": "Logistik Pembersihan", "currentStock": 400, "minThreshold": 150, "unit": "KG", "description": "Deterjen cair"},
    {"id": "item-028", "name": "Sabun Mandi Antiseptik", "categoryId": "logistik-kesehatan", "category": "Logistik Kesehatan", "currentStock": 350, "minThreshold": 120, "unit": "BUAH", "description": "Sabun mandi antiseptik"},
    {"id": "item-029", "name": "Shower Cap", "categoryId": "logistik-perkantoran", "category": "Logistik Perkantoran", "currentStock": 200, "minThreshold": 60, "unit": "BUAH", "description": "Shower cap"},
    {"id": "item-030", "name": "Hair Dryer Portabel", "categoryId": "logistik-perkantoran", "category": "Logistik Perkantoran", "currentStock": 30, "minThreshold": 10, "unit": "BUAH", "description": "Hair dryer portabel"},
    {"id": "item-031", "name": "Setrika Listrik", "categoryId": "logistik-perkantoran", "category": "Logistik Perkantoran", "currentStock": 25, "minThreshold": 8, "unit": "BUAH", "description": "Setrika listrik"},
    {"id": "item-032", "name": "Kipas Angin Mini", "categoryId": "logistik-perkantoran", "category": "Logistik Perkantoran", "currentStock": 40, "minThreshold": 15, "unit": "BUAH", "description": "Kipas angin mini"},
    {"id": "item-033", "name": "AC Portabel", "categoryId": "logistik-perkantoran", "category": "Logistik Perkantoran", "currentStock": 15, "minThreshold": 5, "unit": "BUAH", "description": "AC portabel"},
]

EXPECTED_ITEM_COUNT = 33

INCIDENT_TYPES = ["Banjir", "Kebakaran", "Tanah Longsor", "Angin Kencang", "Kekeringan", "Lainnya"]

SAMPLE_DISTRIBUTIONS = [
    {"item_id": "item-001", "quantity": 40, "destination": "Posko Martapura Timur", "incident_type": "Banjir", "days_ago": 1},
    {"item_id": "item-002", "quantity": 15, "destination": "Posko Martapura Timur", "incident_type": "Banjir", "days_ago": 1},
    {"item_id": "item-022", "quantity": 20, "destination": "Desa Sungai Tabuk", "incident_type": "Banjir", "days_ago": 2},
    {"item_id": "item-005", "quantity": 30, "destination": "Puskesmas Astambul", "incident_type": "Banjir", "days_ago": 3},
    {"item_id": "item-001", "quantity": 25, "destination": "Kecamatan Karang Intan", "incident_type": "Tanah Longsor", "days_ago": 5},
    {"item_id": "item-009", "quantity": 3, "destination": "Pasar Martapura", "incident_type": "Kebakaran", "days_ago": 6},
    {"item_id": "item-017", "quantity": 20, "destination": "Posko Gambut", "incident_type": "Banjir", "days_ago": 8},
    {"item_id": "item-008", "quantity": 25, "destination": "Posko Gambut", "incident_type": "Banjir", "days_ago": 8},
    {"item_id": "item-013", "quantity": 10, "destination": "Desa Aluh-Aluh", "incident_type": "Angin Kencang", "days_ago": 12},
    {"item_id": "item-014", "quantity": 60, "destination": "Desa Aluh-Aluh", "incident_type": "Angin Kencang", "days_ago": 12},
    {"item_id": "item-001", "quantity": 30, "destination": "Kecamatan Pengaron", "incident_type": "Kekeringan", "days_ago": 18},
    {"item_id": "item-026", "quantity": 15, "destination": "Posko Simpang Empat", "incident_type": "Banjir", "days_ago": 24},
]
